databaseChangeLog:
  - changeSet:
      id: product-category-1
      author: Joban
      changes:
        - createTable:
            tableName: category
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: category_pkey
              - column:
                  name: description
                  type: varchar(50)
              - column:
                  name: created_date
                  type: timestamp
              - column:
                  name: last_modified_date
                  type: timestamp
        - createTable:
            tableName: product_category
            columns:
              - column:
                  name: product_id
                  type: SERIAL
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: product_category_cpkey
              - column:
                  name: category_id
                  type: SERIAL
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: product_category_cpkey
        - addForeignKeyConstraint:
            baseColumnNames: product_id
            baseTableName: product_category
            constraintName: pc_product_id_fk
            referencedColumnNames: id
            referencedTableName: product
        - addForeignKeyConstraint:
            baseColumnNames: category_id
            baseTableName: product_category
            constraintName: pc_category_id_fk
            referencedColumnNames: id
            referencedTableName: category

