databaseChangeLog:
  - changeSet:
      id: product-quantity-1
      author: Joban
      changes:
        - addColumn:
              tableName: product
              columns:
                - column:
                    name: quantity_on_hand
                    type: decimal

        - addDefaultValue:
            tableName: product
            columnName: quantity_on_hand
            columnDataType: decimal
            defaultValueNumeric: 0
            schemaName: public

        - update:
            tableName: product
            schemaName: public
            columns:
              - column:
                  name: quantity_on_hand
                  value: 10

